import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  Header  from "@/components/layout/header";
import Footer from "@/components/layout/footer";
// import SideBar from "@/components/layout/sidebar";
// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
// import Home from "./page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
          <Header />
        <main className="w-full">
      {/* <Home /> */}
          {children}
      
    </main>
        <Footer />
      </body>
    </html>
  );
}
